from tools.compliance.frameworks import (
    get_framework,
    get_control_for_test
)


def categorize_test(test_description: str) -> str:
    desc = test_description.lower()

    # Must check "login" context BEFORE "log"
    if "sql" in desc or "injection" in desc or "xss" in desc:
        return "invalid_login"
    elif "lock" in desc:
        return "lockout"
    elif "timeout" in desc or "session" in desc:
        return "session"
    elif "invalid" in desc or "wrong" in desc or "incorrect" in desc:
        return "invalid_login"
    elif "empty" in desc or "blank" in desc:
        return "invalid_login"
    elif "access" in desc or "permission" in desc:
        return "access_control"
    elif "audit" in desc:
        return "audit"
    elif "valid" in desc or "login" in desc or "credential" in desc:
        return "authentication"
    else:
        return "authentication"


def build_traceability_matrix(
    framework_name: str,
    test_data: dict,
    feature: str
) -> dict:
    framework = get_framework(framework_name)

    matrix = {
        "framework": framework_name,
        "framework_full_name": framework["name"],
        "feature": feature,
        "mappings": [],
        "coverage": {}
    }

    all_tests = []
    for category in ["valid_data", "invalid_data", "edge_cases"]:
        for item in test_data.get(category, []):
            desc = item.get("description", "Unknown test")
            all_tests.append(desc)

    covered_controls = set()

    for test_desc in all_tests:
        test_category = categorize_test(test_desc)
        control = get_control_for_test(framework_name, test_category)

        if control:
            matrix["mappings"].append({
                "test": test_desc,
                "control_id": control["id"],
                "control_title": control["title"],
                "control_description": control["description"],
                "status": "Covered"
            })
            covered_controls.add(control["id"])
        else:
            matrix["mappings"].append({
                "test": test_desc,
                "control_id": "N/A",
                "control_title": "No mapped control",
                "control_description": "Informational test only",
                "status": "Informational"
            })

    all_controls = framework.get("controls", {})
    total_controls = len(all_controls)
    covered_count = len(covered_controls)

    matrix["coverage"] = {
        "total_controls": total_controls,
        "covered_controls": covered_count,
        "coverage_percent": round(
            (covered_count / total_controls * 100)
            if total_controls > 0 else 0, 1
        ),
        "uncovered": [
            {"id": ctrl["id"], "title": ctrl["title"]}
            for key, ctrl in all_controls.items()
            if ctrl["id"] not in covered_controls
        ]
    }

    return matrix


def format_matrix_report(matrix: dict) -> str:
    if matrix["framework"] == "None":
        return "No compliance framework selected."

    lines = []
    lines.append("=" * 60)
    lines.append("COMPLIANCE TRACEABILITY MATRIX")
    lines.append("=" * 60)
    lines.append(f"Framework : {matrix['framework']}")
    lines.append(f"Full Name : {matrix['framework_full_name']}")
    lines.append(f"Feature   : {matrix['feature']}")
    lines.append("")

    cov = matrix["coverage"]
    lines.append(
        f"Coverage  : {cov['covered_controls']}/"
        f"{cov['total_controls']} controls "
        f"({cov['coverage_percent']}%)"
    )
    lines.append("")
    lines.append("-" * 60)
    lines.append("TEST TO CONTROL MAPPINGS")
    lines.append("-" * 60)

    for m in matrix["mappings"]:
        lines.append(f"\nTest   : {m['test']}")
        lines.append(
            f"Control: {m['control_id']} — {m['control_title']}"
        )
        lines.append(f"Status : {m['status']}")

    if cov["uncovered"]:
        lines.append("")
        lines.append("-" * 60)
        lines.append("⚠️  COMPLIANCE GAPS — TESTS NEEDED")
        lines.append("-" * 60)
        for u in cov["uncovered"]:
            lines.append(f"  ⚠️  {u['id']} — {u['title']}")

    lines.append("")
    lines.append("=" * 60)
    lines.append("Generated by TestGen AI Compliance Module")
    lines.append("Built by Ahtsham Ijaz | Senior QA Lead")
    lines.append("=" * 60)

    return "\n".join(lines)
