# tools/markdown_export.py
import os
from datetime import datetime


def export_to_markdown(
    user_story: str,
    test_cases: str,
    playwright_tests: str,
    jira_tickets: list
) -> str:
    """
    Exports everything to a professional markdown file
    """

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"qa_report_{timestamp}.md"
    output_dir = "generated"
    os.makedirs(output_dir, exist_ok=True)
    filepath = os.path.join(output_dir, filename)

    content = f"""# QA Test Report
Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
Generated by: QA Copilot Agent v2.0

---

## 📋 User Story
{user_story}

---

## 🧪 Test Cases
{test_cases}

---

## 🎭 Playwright Tests
```javascript
{playwright_tests}
```

---

## 🎫 Jira Tickets Created
{chr(10).join([f"- ✅ {ticket}" for ticket in jira_tickets])}

---
*Generated by QA Copilot Agent | github.com/Ahtsham-QA*
"""

    with open(filepath, "w") as f:
        f.write(content)

    print(f"  ✅ Report saved: {filepath}")
    return filepath


if __name__ == "__main__":
    export_to_markdown(
        user_story="User can login",
        test_cases="## TEST CASE 1: Valid Login",
        playwright_tests="test('login', async ({ page }) => {})",
        jira_tickets=["SCRUM-1", "SCRUM-2"]
    )